### ISSUE TITLE
Shelly Plug S 

### ISSUE THREAD

**Issue by MajkiIT** [enesbcs/Shelly_MQTT#10]
Do you plan add support to Shelly Plug S?

**Comment by enesbcs** [comment]
As soon as i get a Shelly Plug S, yes... :) My Shelly Plug works fine.

**Comment by MajkiIT** [comment]
if I give you donate on Paypal you will be able to buy?

**Comment by enesbcs** [comment]
I am currently negotiating with Allterco about shipping sample pieces of Shelly EM, Shelly Plug S and Shelly 2.5. I will let you know about it's status.

**Comment by MajkiIT** [comment]
Ok, Can you give me URL to your request on Facebook?

**Comment by enesbcs** [comment]
https://www.facebook.com/groups/ShellyIoTCommunitySupport/permalink/2135048569927829/

**Comment by enesbcs** [comment]
Shelly Plug S path includes "-" "shellyplug-s-XXXXXX" as per http://www.domoticz.com/forum/viewtopic.php?f=65&t=25656&sid=22d2090395894af07bb2d5066c000170&start=100#p217540 some kind of workaround needed...

**Comment by damsma** [comment]
Here is an possible fix:
![grafik](https://user-images.githubusercontent.com/45398732/59864669-a46d3800-9387-11e9-9ffc-40b76e232709.png)

**Comment by enesbcs** [comment]
Thank you for suggestion, it is  included in commit https://github.com/enesbcs/Shelly_MQTT/commit/c9810fcbfa9649dc2264d3b6bbda730d1f8afd2d
I hope Allterco will avoid further usage of "-" in MQTT paths...

**Comment by MajkiIT** [comment]
@enesbcs @damsma Now it's working excellent. Thank you for your help.

**Comment by enesbcs** [comment]
Thanks for feedback, issue is closing now as it is solved.
Feel free to reopen in case of a related problem.

**Comment by kzyapkov** [comment]
Noted, I'll see if we can change the device identifier with a FW update, but this may cause more problems than it solves.

**Comment by enesbcs** [comment]
Thanks, currently it is solved inside this plugin for "shellyplug-s". If it is possible avoid "-" usage in future device mqtt paths, current names are OK for now. :)
