### ISSUE TITLE
New feature request: Shelly EM support

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#11]
Reference to:
http://www.domoticz.com/forum/viewtopic.php?f=65&t=25656&start=80#p215919

**Comment by blazoncek** [comment]
I have just submitted a pull request.

**Comment by enesbcs** [comment]
As i see, this code is same as the normal Shelly2 energy and power field, am i right?
Could you try instead to replace instead only this 2 line in the original code:
```
         # RELAY type, not command->process
         if (len(mqttpath)>3) and (mqttpath[2] == "relay") and ("/command" not in topic):
```
To that?
```
         # RELAY and EMETER type, not command->process
         if (len(mqttpath)>3) and (mqttpath[2] in ["relay","emeter"]) and ("/command" not in topic):
```

**Comment by blazoncek** [comment]
Done, but please double check it.
The code is a mess. :)

The code differs in voltage part, everything else looks the same as 1PM/2.5/4Pro. Not Shelly2 though.

**Comment by enesbcs** [comment]
Thanks, merged. There were a missing :, but it seems fine, altough i do not own an EM for testing.
