### ISSUE TITLE
Two blinds created (venetian and percentage)

### ISSUE THREAD

**Issue by joba-1** [enesbcs/Shelly_MQTT#14]
I have one shelly 2.5. 
It is in roller shutter mode.
Autodiscovery of your plugin detects 2 switch devices.
I think it should be only one: the percentage type, not the venetian.

P.S.: nice work, very appreciated Thanks!

**Comment by enesbcs** [comment]
Auto-discovery works upon arrived MQTT messages, if a /roller status arrives it creates a venetian if a /pos status arrives it creates a percentage positional device. If all of it arrives than all 2 is created. You can set to non-used one of them.

**Comment by joba-1** [comment]
ok, will do.
