### ISSUE TITLE
Inverted logic compared to shelly web ui

### ISSUE THREAD

**Issue by joba-1** [enesbcs/Shelly_MQTT#17]
I have a shelly 2.5, configured as roller shutter.

With the web ui of the shelly, I can control it like normal:
* press open: shutter opens (goes up), 
* press close: shutter closes (goes down) 
The percentage means percent opened (100% is fully open).

I have not configured any logic inversion for the inputs in shelly web ui nor in domotic device type or in your plugin, so I would expect the domoticz control works the same as shelly web ui.

What happens is this: 
* pressing domoticz switch open symbol -> shutter goes down (wrong)
* pressing domoticz switch close symbol -> shutter goes up (wrong)
* set domoticz switch slider to 75% -> shutter goes to 75% up/open (expected)
* The position reported by the shelly after that is also (close to) 75% (expected)

Open/close is also switched for the venetian blinds type of switch that is also autocreated.

**Comment by joba-1** [comment]
if I use the global invert setting from your plugin, open and close work as expected, but a fully opened shutter is reported as closed and vice versa.

**Comment by enesbcs** [comment]
Thanks for the Pull request i have merged it, we will see what other users experience...

**Comment by joba-1** [comment]
Fair enough. If other users need it differently, I have no problem using my fork. Thanks for your work!
Leaving issue open for other users comments, but feel free to close...

**Comment by josemi73** [comment]
Same behaviour as joba-1. 

> if I use the global invert setting from your plugin, open and close work as expected, but a fully opened shutter is reported as closed and vice versa.

**Comment by joba-1** [comment]
Hi @josemi73,

Since commit 60bd613df1182d952c717d52cf527c280f79da54 this is fixed for me.
With this version I do not need to enable global inverting in the plugin, open in domoticz or via physical button opens and an open shutter is reported as open.

So, maybe it is most efficient to check differences between our setup, since there are so many ways to configure or wire this.

Do you use a github version of Shelly_MQTT that includes the recent (10 days) change #18?
Have you configured any inversions in the shelly device and is its firmware on latest level (compare to my settings below)?
Do you have 2 physical buttons attached to the shutter and they work as expected?

This is how my shelly is configured:

![image](https://user-images.githubusercontent.com/32450554/60399767-0b4dd680-9b6a-11e9-92b9-ba58c14c6271.png)

**Comment by josemi73** [comment]
Thank you joba-1. That was it. I pulled ShellyMQTT git, and it is working properly now. I was using an old version. World is better now.

**Comment by enesbcs** [comment]
Closed for now as it looks like solved.

**Comment by joba-1** [comment]
at least it still works for me :) Thanx


-- 
iphone so i typo
