### ISSUE TITLE
Energy and Usage fields

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#2]
Shellies has this informations
1. shellies/shellyswitch-<deviceid>/relay/power reports instantaneous power consumption rate in Watts
2. shellies/shellyswitch-<deviceid>/relay/energy reports amount of energy consumed in [10 * Wh]
They need to be combined into one Domoticz device with double value? nvalue:0, svalue "power;energy"? More information (domoticz logs, mqtt messages, data tables) needed to fix issue.

**Comment by enesbcs** [comment]
Thanks for this informations. Just to clarify:
if i combine Watts from "relay/power" and energy from "relay/energy" (in Wh unit) into one single Domoticz device (Unit type="kWh") and passing it to the Domoticz with "svalue": "power;(energy/10)" than it will be OK? 
FYI: Shelly starts counting Energy from 0 after each restart...

**Comment by skorc99** [comment]
as i see from mqtt svalue first position is current value and total usage...

hm do you think tasmota stores internaly total usage? that is not ok if value is reset to 0

**Comment by enesbcs** [comment]
Shelly2 only returns two values, so there are nothing more i can choose... 
1: "power" reports instantaneous power consumption rate in Watts
2: "energy" reports amount of energy consumed in [10 * Wh]
and period. There will be no more informations from the original firmware.
http://shelly-api-docs.shelly.cloud/#shelly2-mqtt
Energy can be added to the previous value, that is stored by the Domoticz server, when Shelly sends an announce message. If they only sends announce messages at startup. But my plugin has to watch and register and store this event and values in memory.

**Comment by skorc99** [comment]
2019-01-09 05:28:12.293 (Shelly) MQTT message: shellies/shellyswitch-134D85/roller/0/command open
2019-01-09 05:28:12.494 (Shelly) MQTT message: shellies/shellyswitch-134D85/roller/0 open
2019-01-09 05:28:12.658 (Shelly) MQTT message: shellies/shellyswitch-134D85/relay/power 34.01
2019-01-09 05:28:12.721 (Shelly) MQTT message: shellies/shellyswitch-134D85/relay/power 104.32
2019-01-09 05:28:14.085 (Shelly) MQTT message: shellies/shellyswitch-134DDD/roller/0 stop
2019-01-09 05:28:14.086 (Shelly) MQTT message: shellies/shellyswitch-134DDD/roller/0/pos 100
2019-01-09 05:28:14.099 (Shelly) MQTT message: shellies/shellyswitch-134DDD/relay/power 0.0
2019-01-09 05:28:28.8

usage is nit send.

device- power is created and if energy metering setting in domiticz is changed to computed it means that domoticz is calculating usage based on power. this is working.

**Comment by enesbcs** [comment]
should we treat this issue as solved?

**Comment by skorc99** [comment]
i have send question for fw update-shelly.

both options are possible.

1.)read value from device   **svalue":"234;1145093.9**
2.)calculate value from power

I will post when i get answer.

For now total usage is not send with MQTT in your script. This is necessary to use:

1.)read value from device   **svalue":"234;1145093.9**

U

**Comment by kzyapkov** [comment]
Hi all,

Allterco fw guy here. There are fixes planned around power and energy consumption -- we've had this going on for a while for our internal cloud implementation. We are trying to make it as easy as possible to get data on energy consumption from the device itself rather than integrating instantaneous power elsewhere. The power metering chips we use are industry-graded, and while it is not possible to fit an industry-grade analog frontend in these form factors they should be capable of getting a much more accurate cumulative reading.

The energy counter is not stored in NVM, so a reboot or power cycle would reset it to zero. Observers should implement logic to handle that, and also handle overflow, however unlikely that is to happen.

We are using Watt-min for our cloud backend, and there was talk about switching the MQTT and HTTP units to that as well -- feedback?

Also, for 1.5 we should have fixed all bugs around those counters, there are some now...

**Comment by enesbcs** [comment]
Hi Kiril!
Thank you for your informations. I guess i can do some kind of dictionary, that reads energy value stored at the Domoticz side when "announce" mqtt msg arrives and adds incoming values from Shelly to it periodically, but this will not work, when plugin will be restarted for any reason or announce send by shellies before the plugin starts.
If we are speaking about announce: there are strange characters (non-alphanumeric?) inside the message that Domoticz mqtt service will not tolerate and error messages popping up periodically, so i am dropping every incoming announce messages now to make them disappear.

Actually my problems is not related to Shelly, but instead Domoticz: in my testings now the "kWh" device, that Domoticz uses fed by the power and energy, sent by the shelly in the format it expects "power;energy" If i can figure out, how to enable "computed" attribute programatically at the time of device creation, than Domoticz will do the hard work instead of the plugin, counting the energy internally.
