### ISSUE TITLE
Readme not up2date

### ISSUE THREAD

**Issue by rutgerrrr** [enesbcs/Shelly_MQTT#24]
Not really an issue but anyway....

Seems like your plugin is more awesome than described in the readme. Reading through fixed issues it and testing with my Shelly 1PM, it seems like you also support Shelly 1PM and also support power measurement and temp on 1PM and probably also on 2. Glad I tried it before building something myself :)

Maybe update the docs?

**Comment by enesbcs** [comment]
As Shelly1 PM is somewhere between Shelly1 and Shelly2.5 i had a feeling that it may work but i dont have this device to test it. Thank you for testing and reporting, i will update the supported devices list.
