### ISSUE TITLE
New feature request: Shelly Flood support

### ISSUE THREAD

**Issue by josemi73** [enesbcs/Shelly_MQTT#25]
Are you planning to add support for new Shelly Flood device? Must I wait to add them to domoticz via MQTT?
Shelly Api reference is not updated with Shelly Flood yet...

**Comment by josemi73** [comment]
Added right now:

https://shelly-api-docs.shelly.cloud/#flood-settings

**Comment by enesbcs** [comment]
Closed by PR
https://github.com/enesbcs/Shelly_MQTT/commit/bae0d4f3151ad8de25c59733d472a7f4a9646af8
