### ISSUE TITLE
Power measure inaccurate? 

### ISSUE THREAD

**Issue by viper1978** [enesbcs/Shelly_MQTT#26]
Since this week I installed a Shelly 1PM to measure the power my hybrid car consumes while charging. 
This is a replacement for a bluetooth Voltcraft plug.
I activated MQTT to be ably to see and write the data to Domoticz. 
For a reference I put the Voltcraft after the Shelly to check if they measure the same.

Today I did a measure and the Voltcraft measured just over 5 kwh where the Shelly measures just over 3 kwh. Pretty sure the Voltcraft is the better measure since the battery is around 6kwh and was not completely empty.

I had the feeling when writing to the cloud the shelly measured more, although I think this would be strange because when I check shelly_IP/status/  the total over there is the same as in Domoticz. Before I started the measure I did a reset of the voltcraft and the shelly to make sure they both started at 0.

**Comment by viper1978** [comment]
I decided to do some more tests.

What I found out is that the measure is going ok. The problem is caused by the way it’s send to domoticz.



I did 2 measures:
1. Shelly connected to cloud and connect a 2kw heater for 10 minutes (see attached file with cloud in the name)
2. Shelly with MQTT enabled and connect the same 2kw heater for 10 minutes (see other attached file)

Both report around the same total, so the measurement is ok.

The only thing I don’t know is how often the MQTT service reports the power, because it looks like not all measures (totals per minute) seem to come over in domoticz.

Any ideas?

[response-stop-cloud kopie.txt](https://github.com/enesbcs/Shelly_MQTT/files/3552765/response-stop-cloud.kopie.txt)
[response-stop kopie.txt](https://github.com/enesbcs/Shelly_MQTT/files/3552766/response-stop.kopie.txt)

**Comment by enesbcs** [comment]
When an MQTT update (with /energy or /power) arrives from the Shelly, my plugin updates the Domoticz device that belongs to it. There are nothing to do on my side in this topic. If you enable Verbose logging in the plugin settings you can see how often the mqtt messages arrives. 
I guess that you have already enabled the Computed energy reading setting in Domoticz.
![Computed](http://mojwlan.net/t/e.PNG)

**Comment by viper1978** [comment]
I didn't use the option Computed yet, will try this. For some reason computed sound less accurate compared to From Device.

Can you tell me how the consumption is translated to Domoticz? If you use timestamp and the total consumption you could calculate an accurate (average) consumption from there. If it's implemented like this is also will correct possible downtime from domoticz.

**Comment by enesbcs** [comment]
The values from mqtt string is translated... ehm forwarded directly to the Domoticz Device. Except the energy field. According to original Shelly API (several months ago) the energy field contains:
"10*Wh" so I've translated it to kwh as (energy/100)
But when i checked out the API one minutes before i see this description:
"reports amount of energy consumed in [Watt-min]"
( https://shelly-api-docs.shelly.cloud/#shelly2-mqtt )

I have no clue when it changed and how it has to be translated (multiplication with 0.06?). The resources which i can work on the link above and this:
https://www.domoticz.com/wiki/Developing_a_Python_plugin
Anything else is just by trial-and-error... Using the LastUpdate field from domoticz device and comparing with python plugin time sounds interesting experiment, but i am not sure that the two time will be the same in every occasion (localized time vs utc), as the Python_plugin documentation is not so talkative.

**Comment by enesbcs** [comment]
As no ideas or feedbacks provided i had to decide on my own: power reading is now an optional feature, it has to be enabled manually on the plugin page.
I am using x0.06 for the wattmin energy conversion, it is selectable if only power or energy also required, i suggest to use Domoticz calculated value.
