### ISSUE TITLE
Shelly dimmer SL support

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#31]

**Comment by enesbcs** [comment]
My Shelly Dimmer SL order postponed to end of December

**Comment by asquelt** [comment]
mine just arrived.
this makes it sing: https://gist.github.com/asquelt/e1acc75707484ff12926d9168481101a
thank you for excellent plugin!

**Comment by enesbcs** [comment]
Preliminary support added in commit https://github.com/enesbcs/Shelly_MQTT/commit/937a70ea6952b84456507d31246216625fb6f51a

**Comment by enesbcs** [comment]
Bad news, my order was cancelled:

Your order on Shelly Cloud has been partially refunded. 
Dimmer SL not available. | -19.99 €

**Comment by TheLion** [comment]
I'm happy to report that the Shelly Dimmer works flawlessly with the latest version. :-)

**Comment by karlzre** [comment]
Hi, 
I confirm also that Shelly Dimmer works perfectly.
I just didn't get the power consumption back to domoticz, is the feature active ?

**Comment by TheLion** [comment]
> 
> 
> Hi,
> I confirm also that Shelly Dimmer works perfectly.
> I just didn't get the power consumption back to domoticz, is the feature active ?

I noticed the same. In the readme of the plugin it is mentioned though:

`Power consumption can be enabled in the plugin settings page manually, it's an optional feature without any further support`

It is visible in MQTT, so maybe in a future version ;-)

**Comment by karlzre** [comment]
Maybe @enesbcs or @asquelt can try to add it ?
should be around line 319 but I have insuffisant python knowledge to do it myself.

`2020-01-17 12:22:08.708 (Shelly MQTT) MQTT message: shellies/shellydimmer-F364B4/light/0/power 27.15
2020-01-17 12:22:08.708 (Shelly MQTT) MQTT message: shellies/shellydimmer-F364B4/light/0/energy 4768
2020-01-17 12:22:08.909 (Shelly MQTT) MQTT message: shellies/shellydimmer-F364B4/light/0/power 29.96
2020-01-17 12:22:08.910 (Shelly MQTT) MQTT message: shellies/shellydimmer-F364B4/light/0/energy 4768`

**Comment by enesbcs** [comment]
> Maybe @enesbcs or @asquelt can try to add it ?
> should be around line 319 but I have insuffisant python knowledge to do it myself.
I have python knowledge, but also have insufficant shelly devices to test.. :) experimental support added at commit https://github.com/enesbcs/Shelly_MQTT/commit/690f55f0cb475fdff80fd4e0806a1ef3346d7b0d
Will be supported after my order arrives, maybe Mach or April, only Allterco knows. :)

**Comment by enesbcs** [comment]
> It is visible in MQTT, so maybe in a future version ;-)

This feature can be enabled at Shelly_MQTT hardware plugin settings, with this: "I am accepting that Power reading may be inaccurate and is totally unsupported, just enable it!:"
It has to be manually enabled once, I do not think that it will change in the near future.

**Comment by karlzre** [comment]
> I have python knowledge, but also have insufficant shelly devices to test.. :) experimental support added at commit 690f55f
Will be supported after my order arrives, maybe Mach or April, only Allterco knows. :)

@enesbcs I can test it for you tonight or tomorrow

**Comment by karlzre** [comment]
@enesbcs you are a king, it works !

https://photos.app.goo.gl/TjWDzDo9zdwizgHr6

**Comment by TheLion** [comment]
I can also confirm it works! Great!

**Comment by enesbcs** [comment]
Great news, thank you for feedback!

**Comment by enesbcs** [comment]
Shelly Dimmer support is now solved, issue is closed.
