### ISSUE TITLE
Shelly door/window sensor support

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#32]

**Comment by enesbcs** [comment]
Door Sensor is on its way now, at least the Bulgarian Post has it. :)

**Comment by enesbcs** [comment]
Added support at commit https://github.com/enesbcs/Shelly_MQTT/commit/5f1524336d3b7358f072a75de03886d1b572b208

**Comment by Janssuhhh** [comment]
Using the latest commit, doorsensor is recognized and works.
Lux-sensor is also registered under Utility and updates as soon as the doorsensor is triggered.

**Comment by enesbcs** [comment]
Thank you for you feedback, issue is now closed as solved.

**Comment by ayasystems** [comment]
Seems works fine.

sensors sends data each 6 hour automatically when no has change of status.

Thanks for your work!!! GREAT plugin. Can i do a paypal donation for you?

Regards

**Comment by enesbcs** [comment]
> Seems works fine.
> 
> sensors sends data each 6 hour automatically when no has change of status.
> 
> Thanks for your work!!! GREAT plugin. Can i do a paypal donation for you?

@ayasystems Thank you for your feedback and offer. Donations can be sent to dedicated ko-fi site https://ko-fi.com/shelly_mqtt (which will be used to buy other shelly devices) or to my other project: RPIEasy. https://www.paypal.me/rpieasy
