### ISSUE TITLE
Shelly bulb

### ISSUE THREAD

**Issue by skorc99** [enesbcs/Shelly_MQTT#33]
Hello is shelly bulb supported?

**Comment by enesbcs** [comment]
In theory it could work, but i do not have such a device for test it.

**Comment by enesbcs** [comment]
Thanks to the ko-fi donators, a Shelly Bulb is now on the way to me, for testing. (EXPECTED SHIPPING | Feb 01, 2020)

**Comment by enesbcs** [comment]
Shelly bulb arrived and i can confirm that it works in Domoticz as an RGBWZ device.
