### ISSUE TITLE
Shelly EM

### ISSUE THREAD

**Issue by Migines** [enesbcs/Shelly_MQTT#36]
Hi, thank you very much for your great work, I'm trying to install an EM shelly with MQTT in Domoticz, but it doesn't work very well. Consumption measurements are not correct. When will you integrate the EM into the plugin? Thank you

**Comment by enesbcs** [comment]
Sorry i do not have this kind of device, so i am unable to integrate it.

**Comment by Migines** [comment]
Thanks

**Comment by enesbcs** [comment]
Update status: A Shelly EM is on its way to me, thanks to Allterco.

**Comment by karlzre** [comment]
Hi,
Any idea if shelly 3EM will be compatible also ?

**Comment by enesbcs** [comment]
Based on the current Shelly MQTT API, there is no distinct 3EM mqtt paths. So I think it works similarly as simple EM, but i will ask after that.

**Comment by enesbcs** [comment]
EXPECTED SHIPPING | Jan 27, 2020

**Comment by enesbcs** [comment]
> Any idea if shelly 3EM will be compatible also ?
I've got info about 3EM: mqtt payloads will be slightly different, but the format is not final yet. We will see.

**Comment by enesbcs** [comment]
Shelly EM is working as expected, issue is closed now. Shelly 3EM issue is separated into https://github.com/enesbcs/Shelly_MQTT/issues/45

**Comment by jurgenvdven** [comment]
> Shelly EM is working as expected, issue is closed now. Shelly 3EM issue is separated into #45

Hi enesbcs,

The shelly EM is indeed working but in my case i would like to measure watt's from solar panels. So for example I get -100watt value's. Domoticz does not count - value's only + value's. Is there a way to replace - by + before putting the value into the database of domoticz?

Thank you!

**Comment by enesbcs** [comment]
Sorry, i do not know. If Domoticz does not count "-" than it is a hard pass from the system.. you can always reverse the clamps...

**Comment by jurgenvdven** [comment]
Yes i know it is possible to reverse the clamps but i also use openhab for testing and i noticed that openhab does count - value's. So i think it might possible to replace - for a + when the plugin recieves the value's or does mqtt send the value's directly to domoticz?

thank you!

**Comment by enesbcs** [comment]
The plugin can translate values that arrived from mqtt to the domoticz device.. the question is, that converting - to + by the plugin is a future-proof solution or maybe the Domoticz will handle - signs in the future and then conversion in the plugin will results unwanted behaviour.

**Comment by jurgenvdven** [comment]
I'm aware of that but at the moment i don't see any signs that they will do that and this a specific config derived from shelly.

The main reason why i preferr - value's for solar is because Shelly will correctly fill it in his own dictonary, see example.

emeters: [
{
power: -160.65,
reactive: -105.72,
voltage: 232.06,
is_valid: true,
total: 4.2,
total_returned: 10114.8
},
{
power: -115.89,
reactive: 131.77,
voltage: 232.06,
is_valid: true,
total: 143.1,
total_returned: 11554.4
}
],

Is it possible to tell me which lines I need to edit? this would be very helpfull!

thank you anyway

**Comment by enesbcs** [comment]
If you want to use absolute values for Domoticz devices:

Line 396
From:
`sval = str(mval)+";"+str(prevdata[1])`
To:
`sval = str(abs(mval))+";"+str(prevdata[1])`

Line 398
From:
`sval = str(mval)+";0"`
To:
`sval = str(abs(mval))+";0"`

Line 404
From:
`sval = str(prevdata[0])+";"+str(mval2)`
To:
`sval = str(prevdata[0])+";"+str(abs(mval2))`

**Comment by jurgenvdven** [comment]
this is working as it should be! thank you very much!

**Comment by HerreZw** [comment]
Hi Jurgen,
Where did you enter the code? I'm a newby in Domoticz and really happy that I got the Shelly EM working with my solarpanels. Domoticz is showing me a graph but doesn't count. No totals.
In the end I want to see the total consumption of our household and the energy production in one view. It's a long way for me, but I will get there ;-)
Thanks!

**Comment by enesbcs** [comment]
Option "Use absolute value of energy readings" added in commit https://github.com/enesbcs/Shelly_MQTT/commit/d0ae137948edbcd913c384dad6da04289fa999cb

**Comment by jurgenvdven** [comment]
Hi Herre,

No problem!

Well I assume that you have also installed the shelly plugin in the following directory.
domoticz/var/plugins/Shelly_MQTT

edit plugin.py file using nano or vi on the noticed lines.

@enesbcs,
In my previous post i said that everything is working as expected but the values are indeed converted to absolute values in watt's. But for some reason domoticz does not count the wh's.
Is there a line missing which also needs to be converted to absolute?
 
![image](https://user-images.githubusercontent.com/60699117/75805466-2ec4c300-5d82-11ea-9d66-40aff5c2cc55.png)

**Comment by enesbcs** [comment]
Did you enabled "Power and energy" setting at plugin page? When i was tested v0.4.4 then both values seemed to be positive.

**Comment by enesbcs** [comment]
> **_mval2 = round((mval_0.017),4) # 10_Wh? or Watt-min??_**

Originally this value advertised by 10Wh in the Shelly API. Now it is referenced as Watt/min. 
0.017 modifier is recommended by a user, i have no clue if it is all right. This is one of the reasons why i marked energy reporting as a non-supported feature. It can be used as is.

I  recommend to use kWH device in Domoticz as "computed".
https://www.domoticz.com/forum/viewtopic.php?t=15002

**Comment by jurgenvdven** [comment]
@HerreZw 

I have also this issue which you descibe, but not 7,2 but 5.2. Only for 1 channel. (please let me know if you heard something from shelly)
> There's an other problem, but that's a Shellies thing I guess: without any power from the panels - because it's dark outside- Shelly EM says there's a production of 7,2 watt. Even if I switch of the panels. I don't no why this is happening. I wil ask Shelly.

**Comment by HerreZw** [comment]
@enesbcs That did the trick, thanks for the advice!

> > I recommend to use kWH device in Domoticz as "computed".
> https://www.domoticz.com/forum/viewtopic.php?t=15002

But I have a question. My Shelly EM is not exactly recording the correct values. I calculated that that de EM is registrating power on moments power is not possible (no light on the solar panels). It's not much: 7,2W, but still. When I subtract this afterwards @ 5 minutes interval from Domiticz I have almost the same value from the invertor/convertor of my solar panels (<1%).
I would like to subtract the 7,2W on the spot. Where do I alter your script to achieve this? #sval #mval #mval2? 
Many thanks in advance!

(sorry @jurgenvdven no answer from Shelly yet)

**Comment by enesbcs** [comment]
If you only want to modify the power readings but not the energy field than you have to modify the source like this:

```
           if "power" in subval and self.powerread==2:
            mval = mval - 7.2
            sval = str(mval)+";"+str(prevdata[1])
           elif "power" in subval and self.powerread==1:
            mval = mval - 7.2
            sval = str(mval)+";0"
```

**Comment by HerreZw** [comment]
Just that easy @enesbcs, you're my hero!
