### ISSUE TITLE
New door sensor

### ISSUE THREAD

**Issue by ayasystems** [enesbcs/Shelly_MQTT#39]
Hi

I have two new doors sensor. 

Could you add to the plugin??

Domoticz reports the following error:

`2020-01-18 20:44:00.408 Error: dzVents: Error: (2.4.29) Discarding device. No last update info found: {["lastLevel"]=255, ["data"]={["hardwareName"]="Sheely_test", ["hardwareType"]="Shelly MQTT", ["protected"]=false, ["unit"]=1, ["_state"]="0.0;50;1", ["humidityStatus"]="Comfortable", ["hardwareID"]=0, ["_nValue"]=0, ["dewPoint"]=-9.1999998092651, ["humidity"]=50, ["hardwareTypeValue"]=94, ["icon"]="temperature", ["temperature"]=0}, ["rawData"]={"0.0", "50", "1"}, ["baseType"]="device", ["switchTypeValue"]=0, ["deviceID"]="", ["batteryLevel"]=0, ["signalLevel"]=0, ["protected"]=false, ["subType"]="THGN122/123/132, THGR122/228/238/268", ["lastUpdate"]="", ["switchType"]="On/Off", ["deviceType"]="Temp + Humidity", ["timedOut"]=false, ["name"]="Sheely_test - shellydw-F3B2D8-sensor", ["changed"]=true, ["id"]=246, ["description"]=""}`

The MQTT structure is the follow

OPEN
```
shellies/shellydw-F3B2D8/online true
shellies/shellydw-F3B2D8/sensor/state open
shellies/shellydw-F3B2D8/sensor/lux 15
shellies/shellydw-F3B2D8/sensor/battery 96
shellies/shellydw-F3B2D8/online false
```

CLOSE
```
shellies/shellydw-F3B2D8/online true
shellies/shellydw-F3B2D8/sensor/state open
shellies/shellydw-F3B2D8/sensor/lux 31
shellies/shellydw-F3B2D8/sensor/battery 96
```

Do you need aditional info??

Could i help you in any thing?

Best regards!

**Comment by enesbcs** [comment]
duplicated issue https://github.com/enesbcs/Shelly_MQTT/issues/32
