### ISSUE TITLE
add Shelly Smoke support

### ISSUE THREAD

**Issue by skorc99** [enesbcs/Shelly_MQTT#4]
Is possible to add:

Shelly Smoke
Smart Wi-Fi Smoke and Temperature Sensor

**Comment by enesbcs** [comment]
In theory it is possible, as i wrote here at the first line:
https://github.com/enesbcs/Shelly_MQTT/blob/master/README.md

**Comment by enesbcs** [comment]
It is 39.99 € and currently out of stock, so this will not be solved recently.

**Comment by enesbcs** [comment]
I am really sorry, but Allterco informed me that they are unable to provide me a Shelly Smoke for testing. So this issue seems to fall into "wontfix" category for now.
