### ISSUE TITLE
Temperature Sensor Addon for Shelly 1/1PM

### ISSUE THREAD

**Issue by Wasteproberen** [enesbcs/Shelly_MQTT#41]
Will there be another update with support? for the Addon for Shelly Temperature Sensor 1 / 1PM  https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312) because this will be great .

Thanks in advance.

**Comment by enesbcs** [comment]
It can be done, however i did not see any MQTT API regarding this feature.
https://shelly-api-docs.shelly.cloud/#shelly1-1pm-mqtt

**Comment by kzyapkov** [comment]
Oops, we overlooked these. External sensors will be reported on MQTT with v1.6, hopefully to be released within a couple of weeks.

**Comment by enesbcs** [comment]
Thank you for your feedback, we are awaiting 1.6. :)

**Comment by Wasteproberen** [comment]
I think the correct information is now on the site.

Shelly1 and Shelly1PM uses the following topics, where <model> is either shelly1 or shelly1pm:

shellies/shelly1-<deviceid>/relay/0 to report status: on or off
shellies/shelly1-<deviceid>/relay/0/command accepts on, off or toggle and applies accordingly
shellies/shelly1-<deviceid>/input/0 reports the state of the SW terminal
shellies/shelly1-<deviceid>/longpush/0 reports longpush state as 0 or 1
Shelly1PM adds:

shellies/shelly1pm-<deviceid>/relay/0/power reports instantaneous power
shellies/shelly1pm-<deviceid>/relay/0/energy reports an incrementing energy counter in Watt-minute
shellies/shelly1pm-<deviceid>/temperature reports internal device temperature in °C
shellies/shelly1pm-<deviceid>/temperature_f reports internal device temperature in °F
shellies/shelly1pm-<deviceid>/overtemperature reports 1 when device has overheated, normally 0
If Shelly1/1PM is equipped with a temperature add-on, following topics are published as well:

For add-ons with DS1820 sensors:

shellies/<shellymodel>-<deviceid>/ext_temperature/<i> where <i> is the sensor id [0,1,2]: reports temperature in °C
shellies/<shellymodel>-<deviceid>/ext_temperature_f/<i> where <i> is the sensor id [0,1,2]: reports temperature in °F
For add-ons with a DHT22 sensor, in addition to the temperature topic above, a humidity topic is published too:

shellies/<shellymodel>-<deviceid>/ext_humidity/0 reports humidity in percent

**Comment by enesbcs** [comment]
i have a bad feeling that ext_temperature arrives before ext_humidity, so i have no chance to guess the device type on the first message... (Temperature or Temperature+Humidity)

**Comment by enesbcs** [comment]
Temperature and humidity support added as separated Domoticz devices at commit https://github.com/enesbcs/Shelly_MQTT/commit/9bad52da8617f5133e7a13077a411e56bb5aad35

**Comment by Wasteproberen** [comment]
I think it works well. 


307 | IP | shelly1pm-******-0-temp | 173 | Slaapkamer | Temp | LaCrosse TX3 | 25.3 C

Thanks for adding

**Comment by enesbcs** [comment]
Thank you for testing it, issue is closed now, as implemented.
