### ISSUE TITLE
Dimmer value in Domoticz updates when no change

### ISSUE THREAD

**Issue by rolfie23** [enesbcs/Shelly_MQTT#42]
The plugin works great, only I have a little thing that is working but maybe it can be perfectioniced.

In the log of the switch, you get every 30 seconds the state of the switch. I assume Shelly sends this command true MQTT every 30 seconds and your plugin picks this up. I use the log to sometimes check when the light turned off, on, or witch percentage. Which is now impossible to look through.

Is it possible to filter the state, and when it's already that state, don't show it in domoticz?

It's about an Shelly dimmer.

Kind regards

**Comment by enesbcs** [comment]
Yes, possible. Added in commit https://github.com/enesbcs/Shelly_MQTT/commit/6120dec8905a5fa497dc7deb1626d051dd6d26f0

**Comment by rolfie23** [comment]
Thnx, made adjustments and it's working great now!

**Comment by rolfie23** [comment]
One question left, what does the disco mode mean? Everytime when starting an operation it shows it.
![Screenshot_20200214-224234~2](https://user-images.githubusercontent.com/61058985/74569796-8e962e00-4f7b-11ea-8a29-d3e2592b4d37.png)

**Comment by enesbcs** [comment]
I have no idea. If you open your dimmers IP address, than you will see effects in settings on the WebGUI, maybe it is involved.

**Comment by rolfie23** [comment]
Okay can't find. It's an empty message now. I will leave it there.
