### ISSUE TITLE
Scripted commands not sent to channel 2 on shelly-switch

### ISSUE THREAD

**Issue by zzattack** [enesbcs/Shelly_MQTT#44]
I tried to script behavior where toggling an input on one device (say a shelly1) causes toggling of outputs on another device (in my case: both relays on a shelly-switch):

```
import DomoticzEvents as dom
if dom.changed_device_name == 'shelly1_input':
    cmd = 'On' if dom.Devices['shelly1_input'].n_value else 'Off'
    dom.Command("shellyswitch_relay1",  cmd)
    dom.Command("shellyswitch_relay2", cmd)
```

Each mentioned device was properly discovered from the Shelly_MQTT plugin. The script executes whenever the physical switch is toggled, and the 'shellyswitch_relay1' device properly reflects the 'shelly1_input' state, but nothing happens with 'shellyswitch_relay2'. 
I've verified this with 2 separate shellyswitch devices, both running latest `20200206-083100/v1.5.10@e6a4205e` firmware.

I've also monitored with mqtt-spy on `shellies/shellyswitch25-XXXXXX/relay/+/command`, which confirms that only `../relay/0/command` receives a message, but `../relay/1/command` does not. When manually toggling relay 2 from the domoticz UI, everything works fully as expected, i.e. the relay switches and a message on `../relay/1/command` is indeed observed.

Changing the order of the `dom.Command()` calls makes no difference.

My apologies if this is not a defect in the plugin. I am not sufficiently proficient with domoticz to further pinpoint the precise cause and rule out faulty behavior from either the plugin or domoticz itself.

**Comment by enesbcs** [comment]
I am tested with the following dzVents script and it works as expected:

```
return {
	on = {
		devices = {
			'shelly1_input'
		}
	},
	execute = function(dz, switch)
        if (dz.devices('shelly1_input').state == 'On') then
            dz.devices('shellyswitch_relay1').switchOn()
            dz.devices('shellyswitch_relay2').switchOn()
        else
            dz.devices('shellyswitch_relay1').switchOff()
            dz.devices('shellyswitch_relay2').switchOff()
        end
	end
}
```

So your question is not plugin-related.

**Comment by zzattack** [comment]
On both my shelly switches' channel 2 I had a name conflict with a temperature zone. This caused my issue. Apologies for the waste of time.
