### ISSUE TITLE
Shelly 3EM support

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#45]
There are no informations about Shelly 3EM API, support status is unknown.

**Comment by enesbcs** [comment]
Supported:
    shellies/shellyem3-<deviceid>/emeter/<i>/power instantaneous active power in Watts
    shellies/shellyem3-<deviceid>/emeter/<i>/energy energy counter in Watt-minute
    shellies/shellyem3-<deviceid>/emeter/<i>/reactive_power instantaneous reactive power in Watts
    shellies/shellyem3-<deviceid>/emeter/<i>/returned_energy energy returned to the grid in Watt-minute
    shellies/shellyem3-<deviceid>/emeter/<i>/voltage grid voltage in Volts
    shellies/shellyem3-<deviceid>/emeter/<i>/current current in Amps

Currently not supported:
    shellies/shellyem3-<deviceid>/emeter/<i>/total total energy in Wh (accumulated in device's non-volatile     
    shellies/shellyem3-<deviceid>/emeter/<i>/total_returned total energy returned to the grid in Wh 
    shellies/shellyem3-<deviceid>/emeter/<i>/pf power factor (dimensionless)

I do not know how and what kind of Domoticz device will be the best for holding these values...    
https://www.domoticz.com/wiki/Developing_a_Python_plugin#Available_Device_Types

**Comment by enesbcs** [comment]
Closed as no feedback provided

**Comment by karlzre** [comment]
Hi, 
I just installed my shelly 3EM yesterday.
I saw you post and updated my shelly plug in and magic happend, total just appear in domoticz.

Good job!!

One last question, is it possible to get the total of the 3 phases ?

**Comment by enesbcs** [comment]
As Shelly returns all data per channel i doubt that it can be done easily. Perhaps you can sum it inside Domoticz with LUA to a new virtual device.
