### ISSUE TITLE
Shelly EM topics

### ISSUE THREAD

**Issue by toms16** [enesbcs/Shelly_MQTT#46]
Hi, thank you very much for your work. I installed an EM shelly with MQTT in Domoticz, it work OK, but display only 3 parameters on each emeter topic: **power, rpower** and **voltage**. My shelly EM provide also **energy, returned_energy, total** and **total_returned** parameters. Can they be integrated with Domoticz?

![ME topics](https://user-images.githubusercontent.com/6465262/75632707-16786b00-5bff-11ea-8515-142a2a49af6c.png)

**Comment by enesbcs** [comment]
Surely you had overlooked the fact that "energy" and "returned_energy" is combined in the existing Domoticz devices as "kWh" contains "power;energy". So it is already implemented.

But otherwise yes, "total" and "total_returned" is not mentioned in the official API, so it is not implemented:
https://shelly-api-docs.shelly.cloud/#shelly-em-mqtt

**Comment by toms16** [comment]
Could you reopen this issue - I just writing some new information.... 
:-)

Regards,
toms16

------ Wiadomość oryginalna ------
Od: "Alexander Nagy" <notifications@github.com>
Do: "enesbcs/Shelly_MQTT" <Shelly_MQTT@noreply.github.com>
DW: "Tom" <test@logott.pl>; "Author" <author@noreply.github.com>
Data: 03.03.2020 19:09:42
Temat: Re: [enesbcs/Shelly_MQTT] Selly EM topics (#46)

**Comment by toms16** [comment]
I know that Domoticz combines information from sensors to obtain the value of consumed energy (Energy in kWh) and current consumed power (Power in Watts).
However, I did a few simple tests to check the quality of the data saved by Domoticz.

It seems to me that the author did not predict the situation in which Domoticz works all the time, and the sensors do not send data. 

In this situation, Domoticz assumes that for the entire time to the next measurement from the sensor is consumption (Power Usage) with the value of the last measurement, which distorts the value of energy consumption (Energy Usage).
As can be seen in the attached chart, the last measurement before switching off sensor (point A) took place on March 3 at 01:00, and the next (point B – switching sensor on) on March 3 at 17:40. 
Domoticz decided that all this time consumption (Power Usage) was at the level of about 80 W and calculated energy consumption (Energy Usage) of 1.459 kWh, which is obviously not true.
If we compare it with the total parameter from Shelly EM (value 726.9 Wh = 0.73kWh) then we have a big difference. The total value from shelly is correct (I downloaded the sensor data using its application and confirmed it). If I turned on shelly sensor 2 days later Domoticz would show consumption at the level of several kWh ...
That is why I asked about the possibility of integrating the "total" parameter to Domoticz in Shelly_MQTT.

By the way, the manufacturer Shelly is not consistent in his documentation - "total" and "total_returned" is not mentioned in the official API, but in the documentation as much as possible:
https://shelly-api-docs.shelly.cloud/#shelly-em-relay-0

![shelly_total](https://user-images.githubusercontent.com/6465262/75808645-b9f48780-5d87-11ea-8230-26f3ccad2c67.png)

**Comment by enesbcs** [comment]
> It seems to me that the author did not predict the situation in which Domoticz works all the time, and the sensors do not send data.

If you see data from Domoticz Shelly plugin you have accepted this setting:
"I am accepting that Power reading may be inaccurate and is totally unsupported, just enable it!"

So sorry, but this means that i have neither resources, nor time to deal with this unsupported feature. Values arrived from Shellies translated and forwarded to Domoticz as is, without further processing. If anybody has time and python knowledge, can implement this.

**Comment by svde** [comment]
> But otherwise yes, "total" and "total_returned" is not mentioned in the official API, so it is not implemented:
> https://shelly-api-docs.shelly.cloud/#shelly-em-mqtt

Looks like the official API documentation has been updated and now contains the total and total_returned. Would be much appreciated if this count be added to this plugin.

shellies/shellyem-X/relay/0 off
shellies/shellyem-X/emeter/0/power 4.08
shellies/shellyem-X/emeter/0/reactive_power -34.36
shellies/shellyem-X/emeter/0/voltage 230.42
shellies/shellyem-X/emeter/1/power 0.00
shellies/shellyem-X/emeter/1/reactive_power 0.00
shellies/shellyem-X/emeter/1/voltage 230.42
shellies/shellyem-X/emeter/0/energy 18
shellies/shellyem-X/emeter/0/returned_energy 0
**shellies/shellyem-X/emeter/0/total 1472.0**
shellies/shellyem-X/emeter/0/total_returned 0.0
shellies/shellyem-X/emeter/1/energy 0
shellies/shellyem-X/emeter/1/returned_energy 0
shellies/shellyem-X/emeter/1/total 0.0
shellies/shellyem-X/emeter/1/total_returned 0.0

The 1pm does seem to be reporting correctly via this plugin.

shellies/shelly1pm-X/relay/0 off
shellies/shelly1pm-X/input/0 0
shellies/shelly1pm-X/input_event/0 {"event":"","event_cnt":0}
shellies/shelly1pm-X/relay/0/power 0.00
shellies/shelly1pm-X/temperature 42.46
shellies/shelly1pm-X/temperature_f 108.42
shellies/shelly1pm-X/overtemperature 0

**Comment by mattmansm** [comment]
I'd also really appreciate the 'total' number pulled into Domoticz! Thanks

**Comment by enesbcs** [comment]
total added in commit https://github.com/enesbcs/Shelly_MQTT/commit/ae2c1366660f9638e906d958c2595bd298d74de4

**Comment by svde** [comment]
It works for my em + em3 devices. I am seeing strange behavior with my 1pm device. The "total" usage is added in domoticz on a daily basis. [Screenshot](https://www.eijk.nu/se/Annotation%202020-07-01%20141348.jpg), take note of the usage in the last 24 hours, it consumed 2-3W from 03:00-05:00, but 5.763KWh is added to the counter. In the database the counter is also off, [screenshot](https://www.eijk.nu/se/Annotation%202020-07-01%20142023.jpgl).

**Comment by enesbcs** [comment]
My plugin just forwards incoming values to Domoticz without further processing.
All mqtt messages need to be recorded near these events for debugging. Only the 1pm has this behavior?

**Comment by svde** [comment]
It may be a glitch in the matrix. The total value isn't sent with MQTT, see post above.

**Comment by enesbcs** [comment]
Could you send me a verbose domoticz log where it can be seen the incoming mqtt messages and the shelly device status update lines?

**Comment by svde** [comment]
It hasn't happened since. I think it's OK to ignore my earlier message. Thanks for implementing the totals counters.

**Comment by enesbcs** [comment]
Issue is now closed as implemented.
