### ISSUE TITLE
What does 'Use absolute value of energy readings' mean?

### ISSUE THREAD

**Issue by Freekers** [enesbcs/Shelly_MQTT#51]
Thank you very much for this plugin!

Question: what does 'Use absolute value of energy readings' mean?
Does it mean, for example, that an energy reading of 75.69 watts is displayed as 76 watts within Domoticz?

Thank you!

**Comment by enesbcs** [comment]
No. Absolute value means the distance from zero. Simply the value without sign for solar panel users.
https://en.wikipedia.org/wiki/Absolute_value

**Comment by Freekers** [comment]
Ah, okay, thanks for your reply!

I guess it's not applicable to Shelly Plug S users but is intended for use with Shelly EM or Shelly 1PM, right? Thanks!
