### ISSUE TITLE
Shelly RGBW2 - Include brightness when setting colors

### ISSUE THREAD

**Issue by bartschermer** [enesbcs/Shelly_MQTT#52]
Using two Shelly RGBW2s with the Shelly_MQTT plugin on Domoticz.
When controlling the colors and the brightness through the Domoticz web GUI this works fine. But when trying to control them with dzVents using the setColor() function the brightness is ignored.
(for reference: https://www.domoticz.com/wiki/DzVents:_next_generation_LUA_scripting#RGBW.28W.29_.2F_Lighting_Limitless.2FApplamp) 

See attached verbose log file (which I've edited with comments), where I first set the brightness through web GUI and then invoke the dzVents script.
[Verbose log file - commented.txt](https://github.com/enesbcs/Shelly_MQTT/files/4433467/Verbose.log.file.-.commented.txt)

I've done a manual test where I published the following message to my MQTT broker, which successfully set the colors and changed the brightness:

shellies/shellyrgbw2-6EA592/color/0/set ({"turn":"on","mode":"color","red":255,"green":122,"blue":59,"white":0,"gain" :100})

In dzVents the workaround is to both use setColor() for controlling the colors and setLevel() for controlling the brightness, which works like expected.

Can the brightness please be included when changing the colors?

**Comment by enesbcs** [comment]
In the first case, the GUI triggers a "Command: Set Level (20)" which is correct and handled in the Shelly_MQTT plugin.

From dzVents example the log file only contains that: "Command: Set Color (100)". Color Temperature is not supported, and Color array has no  'brightness' elements:

```
uint8_t t;     // Range:0..255, Color temperature
uint8_t r;     // Range:0..255, Red level
uint8_t g;     // Range:0..255, Green level
uint8_t b;     // Range:0..255, Blue level
uint8_t cw;    // Range:0..255, Cold white level
uint8_t ww;    // Range:0..255, Warm white level
```

For brightness change try to use dimTo(percentage) or setLevel(percentage) which is also used by the Domoticz GUI.

**Comment by bartschermer** [comment]
A call to setColor() in dzVents is executed by Domoticz via a JSON API call:
/json.htm?type=command&param=**setcolbrightnessvalue**&idx=36&brightness=100&color={"m":2,"t":0,"cw":0,"ww":0,"r":255,"g":255,"b":255}
(see https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Set_a_light_to_a_certain_color_or_color_temperature)

The setcolbrightnessvalue command can include both the brightness value **and** the color array. However, the plugin only switches the color and ignores the brightness. 
My test shows that including the brightness in the MQTT payload to the RGBW2 has the desired effect. 

I thought I'd flag this as it is not the expected behavior when following the information in the Domoticz wiki.
The workaround using setLevel() works indeed, but I took some time troubleshooting the issue and understanding the need for a workaround. So expect more people might run into this.

**Comment by enesbcs** [comment]
> A call to setColor() in dzVents is executed by Domoticz via a JSON API call:
> /json.htm?type=command&param=**setcolbrightnessvalue**&idx=36&brightness=100&color={"m":2,"t":0,"cw":0,"ww":0,"r":255,"g":255,"b":255}
> (see https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Set_a_light_to_a_certain_color_or_color_temperature)

It's a python plugin, so JSON URL will not move this project forward.
Unless the python API will do the same, this issue #wontfix.

https://www.domoticz.com/wiki/Developing_a_Python_plugin#Callbacks

**Comment by bartschermer** [comment]
I'm sorry if I upset you man... I'm not a developer and don't know the first thing about Python. 
Just noticed from an end-user perspective there's a mismatch.

I see what you mean now and will consider flagging it to Domoticz.
Thanks for your feedback!
