### ISSUE TITLE
Shelly Longpress button issue

### ISSUE THREAD

**Issue by raaq1911** [enesbcs/Shelly_MQTT#53]
Hello,

I have issue with Shelly Longpush button function in Domoticz. When I click on physical button - I can see in Domoticz "Longpush" button set to ON. But I can't turn it to OFF. Physical button don't work, and click on switch in Domoticz don't react. Can You help?

**Comment by enesbcs** [comment]
Try to edit switch settings in Domoticz and set it up to automatically turn off by x seconds.
In Mqtt communication did you see Longpush 0 or just 1?

The code section that enabled manual switching of shelly switches was removed because it was interfered with scene execution https://github.com/enesbcs/Shelly_MQTT/issues/38

**Comment by raaq1911** [comment]
> Try to edit switch settings in Domoticz and set it up to automatically turn off by x seconds.
I set 5 second - no effect.
> In Mqtt communication did you see Longpush 0 or just 1?
> 
Where I can see this? In Domoticz log? 
If i click physical button - no new log
If I click a virtual button in Domoticz (still turned on):
2020-04-15 12:15:24.325 Status: User: raq initiated a switch command (36/Shelly - HOL-0-lpush LONGPUSH/Off)
2020-04-15 12:16:24.832 Status: User: raq initiated a switch command (36/Shelly - HOL-0-lpush LONGPUSH/Off)
2020-04-15 12:17:32.055 Status: User: raq initiated a switch command (36/Shelly - HOL-0-lpush LONGPUSH/Off)
2020-04-15 12:17:43.789 Status: User: raq initiated a switch command (36/Shelly - HOL-0-lpush LONGPUSH/Off)

But switch is still ON.
> The code section that enabled manual switching of shelly switches was removed because it was interfered with scene execution #38

**Comment by raaq1911** [comment]
New info, when I click physical button:
Long push:
-long push - on
-relay - off
short push:
-long push - off
-relay on

Short push can turned off a longpush button.

I have enable:
Don't activate if the button is long pushed. Attention: The relay will be switched only after the button is released.

**Comment by enesbcs** [comment]
> Where I can see this? In Domoticz log?

Yes in Domoticz log, when you enable Verbose Debug logging in Shelly_MQTT hardware settings.

> 2020-04-15 12:17:32.055 Status: User: raq initiated a switch command (36/Shelly - HOL-0-lpush LONGPUSH/Off)
> 2020-04-15 12:17:43.789 Status: User: raq initiated a switch command (36/Shelly - HOL-0-lpush LONGPUSH/Off)
> 
> But switch is still ON.

You can press if you like it, but as i wrote earlier: 

> > The code section that enabled manual switching of shelly switches was removed because it was interfered with scene execution #38

So there are nothing in the plugin code that will serve your request to change the state of a device, device state will only change if state report arrives from MQTT.

**Comment by enesbcs** [comment]
> Short push can turned off a longpush button.

Thank you for this information, i have to implement it to the plugin code.

**Comment by enesbcs** [comment]
> New info, when I click physical button:
> Long push:
> -long push - on
> -relay - off
> short push:
> -long push - off
> -relay on
> 
> Short push can turned off a longpush button.
> 
I've tested it and yes, it works by as you described. The short push and long push also controls the relay. Is it a problem? It is done by the firmware, not my plugin.
You can either stop Domoticz completely the long push will trigger the relay. I've just tested with a Shelly 2, firmware  20200601-122836/v1.7.0@d7961837 

> I have enable:
> Don't activate if the button is long pushed. Attention: The relay will be switched only after the button is released.

I do not see such an option.
