### ISSUE TITLE
rgbww

### ISSUE THREAD

**Issue by Gerwin01** [enesbcs/Shelly_MQTT#54]
i have a couple of shelly's rgbww and in the app (android) in can't change te white channel 
i can't choose the withe color 
an i can't change the level 
someone knows what to do 
Gerwin

**Comment by enesbcs** [comment]
In the Domoticz Android application?
https://play.google.com/store/apps/details?id=nl.hnogames.domoticz&hl=en_US

**Comment by Gerwin01** [comment]
yes in the official android app the paid version
you can change only the collor and you can dim the collor 
but can't change to white

**Comment by enesbcs** [comment]
Did you changed to 4xwhite mode from RGB mode, in the Shelly device menu through your web browser?

**Comment by Gerwin01** [comment]
yes i have done that .into the browser i can change everything and works great 
only in the app the problem

**Comment by Gerwin01** [comment]
In the browser is it also a differetnt slider in the app i can't see that one

**Comment by enesbcs** [comment]
If every function work in the Domoticz main GUI but not working only in the mobile application, than i have no idea, maybe you can try the domoticz forums or the domoticz android app github.

**Comment by Gerwin01** [comment]
it looks the slider missing in the app for the white channel .
yes i can ask overthere 
thanks for your response 
Gerwin
