### ISSUE TITLE
Invert roller shutter position in Domoticz

### ISSUE THREAD

**Issue by Milan1989** [enesbcs/Shelly_MQTT#55]
In case of closed roller shutter position Domoticz shows 100% and it should be show 0% as in the Shelly web page. I am attaching two pictures about the problem.

If you need any further info please let me know.
I am available via Viber. Milán Sápi :-)
[
![2020-04-29_21h37_15](https://user-images.githubusercontent.com/35316485/80639395-3d69e680-8a62-11ea-9b25-dfbbabde409f.png)
](url)
![2020-04-29_21h37_58](https://user-images.githubusercontent.com/35316485/80639421-45c22180-8a62-11ea-9eb5-21b7c56f8212.png)

**Comment by enesbcs** [comment]
And if you check the invert checkbox at plugin settings?
https://github.com/enesbcs/Shelly_MQTT/issues/17
https://github.com/enesbcs/Shelly_MQTT/issues/15

**Comment by Milan1989** [comment]
If I checek invert checkbox at plugin the position will be good but the buttons works in revers.
If uncheck the invert checkbox at plugin the position works wrong but the buttons works right.

**Comment by enesbcs** [comment]
Roller shutter inversion was a question that appears again and again, inverted several times vica-and-versa, and as i see there always be some people that it will works opposite way.

You can also invert the whole thing at the Shelly2 web GUI, and you can always rewire it physically.

**Comment by enesbcs** [comment]
The position handling code is at line 172 at plugin.py:

```
           if str(Parameters["Mode1"])=="1": # check if global inversion requested
             pos = str(Level).strip().lower()
           else:
             pos = str(100-Level).strip().lower()

```

**Comment by Milan1989** [comment]
I tried the invert mode on Shelly GUI it did not solve the problem. Position works inverted, buttons works fine.
What should I modify in this code exactly?

**Comment by enesbcs** [comment]
Perhaps instead of this:
```
           if str(Parameters["Mode1"])=="1": # check if global inversion requested
             pos = str(Level).strip().lower()
           else:
             pos = str(100-Level).strip().lower()
```

Try that:
```
           if str(Parameters["Mode1"])=="1": # check if global inversion requested
             pos = str(100-Level).strip().lower()
           else:
             pos = str(Level).strip().lower()
```

**Comment by Milan1989** [comment]
I replaced the code and restart Domoticz but it was no effect. The situation is the same.
My Domoticz version is 2020.02

**Comment by enesbcs** [comment]
Ne tegyél tabulátort python kódba. A szóközök adják meg a különböző szinteket, ha nem megfelelő számú szóköz van előtte, pontosan ilyen szép piros hibákat ír...
