### ISSUE TITLE
Shelly I3 support

### ISSUE THREAD

**Issue by pcfreak1** [enesbcs/Shelly_MQTT#56]
Shelly released an input module called the i3. is there any plans to support this module?

product page: https://shelly.cloud/products/shelly-i3-smart-home-automation-device/

**Comment by pcfreak1** [comment]
the mqtt info might help for adding this device, i got the following info using mqtt explorer:
there is an announce message containing:
`{"id":"shellyix3-A4CF12F474C7","mac":"A4CF12F474C7","ip":"192.168.18.36","new_fw":true, "fw_ver":"20200421-183805/master@d834f204"}`

then there are three inputs with each an input value for on/off and an input event for the following states:
- simple on/off: {"event":"","event_cnt":21} where event is empty with on/off and contains the specification in other actions like below and the event_cnt is how many events there have been
- button short press: {"event":"S","event_cnt":22}
- button long press: {"event":"L","event_cnt":25}
- double short press: {"event":"SS","event_cnt":26}
- triple short press: {"event":"SSS","event_cnt":27}
- short + long press: {"event":"SL","event_cnt":31}
- long + short press: {"event":"LS","event_cnt":33}

all these actions are available for all three the inputs
the mqtt architecture is in the attached picture.
[https://i.imgur.com/Kx9zupQ.png](url)

i hope this helps, if  you need more info, feel free to ask.

**Comment by pcfreak1** [comment]
the on/off already works but all the advanced actions not yet

**Comment by enesbcs** [comment]
Tested and working with:

    Shelly 1 Open Source (relay)
    Shelly 1PM (relay)*
    Shelly Plug (relay)*
    Shelly Plug S (relay)*
    Shelly2 and 2.5 Switch (relay and roller shutter mode, positioning)
    Shelly4 Pro (relay)*
    Shelly H&T
    Shelly RGBW2
    Shelly Flood
    Shelly Door and Window sensor
    Shelly 2LED
    Shelly Dimmer
    Shelly Bulb RGBW
    Shelly EM

I can only support devices that i have. Thank you for your understanding.

**Comment by enesbcs** [comment]
Support added at commit https://github.com/enesbcs/Shelly_MQTT/commit/4a4325d5180978d5f917e7af21c9e788ba8fd2ec

**Comment by pcfreak1** [comment]
i have one working now, works like a charm, thank you!
