### ISSUE TITLE
Shelly RGBW doesn't work in Domoticz 2020.2

### ISSUE THREAD

**Issue by JeroenEeuwes** [enesbcs/Shelly_MQTT#57]
I have a Shelly RGBW and it is added to Domoticz. However, I can't turn it on or off, nor does the colour selection work.

When I use MQTT explorer to publish something like this the RGBW reacts instantly

{
    "mode": "color",
    "red": 255,
    "green": 0,
    "blue": 255,
    "gain": 50,
    "white": 0,
    "effect": 0,
    "turn": "on"
}

**Comment by Gerwin01** [comment]
Hello 
here is it working great ,but not in the app (android)
Gerwin

**Comment by enesbcs** [comment]
Again: Shelly rgbw works in the Domoticz GUI but not working in the Domoticz mobile application?

**Comment by enesbcs** [comment]
> I have a Shelly RGBW and it is added to Domoticz. However, I can't turn it on or off, nor does the colour selection work.

What is the RGBW path you are using? Did you disable custom MQTT prefix?

**Comment by JeroenEeuwes** [comment]
@enesbcs I'm using the Domoticz website on a Raspberry PI3. I do use a custom MQTT prefix. I also use those prefixes for my Shelly Dimmers and Shelly1s and those work just fine. Is the custom prefix not working for the Shelly RGBW?

In MQTTexplorer I can publish to shellies/Keuken-WC-RGB/color/0/set the JSON I posted above and my Shelly RGBW turns pink. 

On the Domoticz website on my Raspberry Pi I can select the same Shelly (it's called "Shelly MQTT - Keuken-WC-RGB-0-rgb" on the Switches page) but nothing happens. It won't turn on, colour doesn't change, nothing.

I also have a Shelly Dimmer (for example called "Shelly MQTT - Keuken-tafel-0-dimmer") and that works fine. I can even rename it to something like "Keuken tafel" and it still works. 

I think the same problem exists for the Shelly 2.5 which I use in Roller mode. Those show up in Domoticz but they won't open or close either.

**Comment by Gerwin01** [comment]
hello it works in the Domoticz gui .
but in the mobile application is it not working
i have ask this question before 
but nobody knows

**Comment by enesbcs** [comment]
> hello it works in the Domoticz gui .
> but in the mobile application is it not working

I am very sorry but i still not know, i am not familiar with working of the mobile application. :(

**Comment by JeroenEeuwes** [comment]
@Gerwin01 sorry, but I don't use the mobile app of domoticz. If it works in one but not the other it does seem more of a problem of the domoticz app.

**Comment by enesbcs** [comment]
>Is the custom prefix not working for the Shelly RGBW?

It is written clearly in the project page: 

Prerequisites
...
**Please do not check "Use custom MQTT prefix" on your device settings page if you want to use this plugin as this will render device detection unusable!**
...

This plugin uses the name of the devices to autodetect them, and to guess the type and what the hell they does. You have to choose whether you want to use this plugin, OR custom MQTT prefixes. You have to disable every custom MQTT, delete all Shelly devices and autolearn them again.

**Comment by JeroenEeuwes** [comment]
@enesbcs Ah, thanks for pointing this out. It's weird it did actually detect the modules and created the correct devices. Well except for them not working. It also works fine for all my dimmers, but perhaps that's just coincidence. 

I'll have to rethink what I want, but at least now I know what I did wrong. Thanks!
