### ISSUE TITLE
switch icon state does not change in domoticz

### ISSUE THREAD

**Issue by jurgenvdven** [enesbcs/Shelly_MQTT#59]
Hi Enesbcs,

I have upgraded domoticz to 2020.2 and it seems that mqtt is working fine but there is one thing that isn't working anymore. I'm not sure if this is an issue between the plugin or domoticz itself.

When I turn off a lamp using domoticz, the lamp will turn off as expected. But the icon state in domoticz is still on. When refresh my webpage the icon in domoticz is turned off. 

Before the upgrade the icons turn off and on almost the same time when i hit the button.

Could this be a domoticz or plugin thing?

thank you!

**Comment by enesbcs** [comment]
As the plugin refreshes the device status, it is not plugin related, its a Domoticz bug.
