### ISSUE TITLE
Can you please add Led Dimmer 2 by Shelly?

### ISSUE THREAD

**Issue by salopette** [enesbcs/Shelly_MQTT#6]
#Hello, thanks for the great extension!
Can you please add Led Dimmer 2 by Shelly?

https://shelly.cloud/wifi-smart-shelly-rgbw-2/

http://shelly-api-docs.shelly.cloud/#rgbw2-mqtt

**Comment by enesbcs** [comment]
As i wrote on the front page: "If you like this project, or you wants to support the development, you can do that with the paypal link above. Or simply send me a Shelly device, that is not already supported, but you wish."

**Comment by enesbcs** [comment]
A sample RGBW2 device is in order, i hope that i can add this kind of device to the supported devices list in the near future.

**Comment by enesbcs** [comment]
Support added in commit https://github.com/enesbcs/Shelly_MQTT/commit/74b1c18451cdada898f9e73c20da9ac50c0009f4
