### ISSUE TITLE
can't see power consumption SHELLY PLUG S

### ISSUE THREAD

**Issue by italoc** [enesbcs/Shelly_MQTT#60]
i have 10 shelly device ad all works great with this plugin but i cant see SHELLY PLUG S instant power consumption

it'a bug?

**Comment by enesbcs** [comment]
Make sure to:
- enable Accept new hardware devices in Domoticz settings
- DISABLE "Use custom MQTT prefix" at the Shelly device options
- enable "I am accepting that Power reading may be inaccurate and is totally unsupported, just enable it!" setting at Shelly_MQTT settings page

**Comment by italoc** [comment]
Works great

Thaks
