### ISSUE TITLE
Energy - RGBW2?

### ISSUE THREAD

**Issue by Gert05** [enesbcs/Shelly_MQTT#63]
Thanks for an excellent plugin.
I'm having trouble getting the power reading from my RGBW2 (in 4x white mode).
Domoticz registers 6 IDX's: 4 white channels, a button and a long press. No power readings.
"Use custom MQTT prefix" NOT ticked.
Do power readings work on RGBW2?

**Comment by enesbcs** [comment]
According the official Shelly API, there are no energy readings sent from the RGBW2:
https://shelly-api-docs.shelly.cloud/#shelly-rgbw2-white-overview

**Comment by Gert05** [comment]
Hmm. Not quite.
I'm running the RGBW2 on latest firmware.
MQTTBox shows the following output for eacht of the 4 (0..3) channels:
`shellies/shellyrgbw2-<deviceID>/white/x/status` with content `{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"mode":"white","brightness":30,"power":1.78,"overpower":false}`
This is documented in https://shelly-api-docs.shelly.cloud/#shelly-rgbw2-white-mqtt
the "power":1.78" is the power, right? Any chance of using this in the plugin?

**Comment by enesbcs** [comment]
I still not see "power" in the documentation...
{
    "ison",             /* whether the output is ON or OFF */
    "has_timer",        /* whether a timer is currently armed for this channel */
    "timer_started",    /* unix timestamp of timer start; 0 if timer inactive or time not synced */
    "timer_duration",   /* timer duration, s */
    "timer_remaining",  /* if there is an active timer, shows seconds until timer elapses; 0 otherwise */
    "mode",             /* "white" */
    "brightness"        /* output brightness, 0..100 */
}
However in the http GET field, it is documented  in the "meters" attribute as power (Watt). Maybe it appeared in the new firmware and the documentation is not up-to-date.

In theory i can implement this someday.

**Comment by enesbcs** [comment]
Support added at https://github.com/enesbcs/Shelly_MQTT/commit/368c9b4744dd341fb05e62f17990d262a7a360f8

**Comment by Gert05** [comment]
Thanks for the swift implementation. That seems to work just fine. I can see a power meter per channel (so 4 in total). Does it support a summarized power as well (all 4 channels combined - as in the rgbw2 web interface)?

**Comment by enesbcs** [comment]
It is not impossible to make a virtual device in Domoticz but will impact the speed of processing mqtt messages. On all 4 channel it needs to reread actual values from Domoticz then add and write to a fifth virtual device... something similar that we discuss in Shelly EM topic yesterday. I am not sure it worth the efforts. https://github.com/enesbcs/Shelly_MQTT/issues/70

**Comment by enesbcs** [comment]
The original issue is solved as energy is now reported.

Added a new issue for sum of power if somebody has idea to do this in the future.
https://github.com/enesbcs/Shelly_MQTT/issues/75
