### ISSUE TITLE
Feature request - heartbeats

### ISSUE THREAD

**Issue by jefft4** [enesbcs/Shelly_MQTT#65]
I'd like to know that my Shellies are alive and well, when they've not been switched on or off for some time.

I see from the MQTT traffic, that the Shelly switches broadcast their input and relay states very frequently (looks like every 30 seconds).  Presumably, the plugin tests this against the last known state and only updates the domoticz switch devices if there's a real change of state; this is correct as we don't want to trigger events in domoticz for non-changes.

Could the plugin create & update a 'heartbeat' device in domoticz for each Shelly?
It could be as simple as putting the timestamp value from the last-received message, regardless of whether the switch state changed or not, into a domoticz counter device.
To generate fewer updates in domoticz, the plugin might check every 10 minutes to see when it last received a message from each Shelly and update the appropriate counter devices.

**Comment by enesbcs** [comment]
> Presumably, the plugin tests this against the last known state and only updates the domoticz switch devices if there's a real change of state; this is correct as we don't want to trigger events in domoticz for non-changes.

Yes, this is the current situation.

> Could the plugin create & update a 'heartbeat' device in domoticz for each Shelly?
> It could be as simple as putting the timestamp value from the last-received message, regardless of whether the switch state changed or not, into a domoticz counter device.
> To generate fewer updates in domoticz, the plugin might check every 10 minutes to see when it last received a message from each Shelly and update the appropriate counter devices.

In theory it is possible. Although there are several logical devices in Domoticz which represents a single real Shelly device, i guess that one heartbeat device per physical device would be the most logical outcome. To achieve this, every logical device code needs to be enhanced to find its own root real device and update that if the last update was was more than x minutes ago.

**Comment by jefft4** [comment]
Agreed, one heartbeat per physical device would be right.  The MQTT message from Shelly devices contains the hexadecimal ID of the physical device as part of the topic.  Would it be possible simply to take that ID from the topic of each incoming MQTT message and store the latest message timestamp against each physical device ID.  Then, one Shelly device ID = one domoticz 'heartbeat' device.
That would, of course, push an update to domoticz every time a Shelly message comes in, which could be quite a lot of traffic.  I guess that could be reduced by storing the last timestamp sent to domoticz against each device and if the incoming message timestamp is >5 minutes after the stored time, then the domoticz heartbeat device is updated, else not.

**Comment by enesbcs** [comment]
Added at commit https://github.com/enesbcs/Shelly_MQTT/commit/368c9b4744dd341fb05e62f17990d262a7a360f8

**Comment by jefft4** [comment]
Pulled 0.5.1 from git, replacing plugin.py.
Testing now... some problems here:
- 'online' devices are created
- existing devices for the relays and buttons are duplicated :-(  (but still seem to work!)
- errors logged by dzVents for 'no lastUpdate info' on the newly-created Shelly relay devices - appears the field is null:
`2020-08-24 11:25:08.225 Error: dzVents: Error: (3.0.11) Discarding device. No last update info found: {["timedOut"]=false, ["signalLevel"]=-1911607776, ["lastUpdate"]="", ["description"]="", ["deviceID"]="", ["lastLevel"]=255, ["id"]=1619, ["name"]="Shelly devices - shelly1-F3A1DB-0", ["switchType"]="On/Off", ["subType"]="Switch", ["data"]={["hardwareType"]="Shelly MQTT", ["_nValue"]=0, ["usedByCamera"]=false, ["icon"]="lightbulb", ["unit"]=8, ["protected"]=false, ["hardwareTypeValue"]=94, ["hardwareID"]=1276468456, ["_state"]="Off", ["maxDimLevel"]=100, ["hardwareName"]="Shelly devices", ["levelVal"]=0}, ["protected"]=false, ["deviceType"]="Light/Switch", ["batteryLevel"]=-1911608192, ["switchTypeValue"]=0, ["rawData"]={"Off"}, ["changed"]=true, ["baseType"]="device"}`
- created multiple instances of the button and relay devices for a Shelly 1, with different unit IDs (relay 2, 8 and button 1, 9) :-(
- longpush devices were not duplicated; haven't tested those yet to see if the originals still work

**Comment by enesbcs** [comment]
>     * existing devices for the relays and buttons are duplicated :-(  (but still seem to work!)
>
>  ["deviceID"]=""
This should never happen. If deviceID field is empty maybe the autodetection phase failed, with some hard errors, and the plugin can not distinguish devices if every device has empty deviceID.

**Comment by enesbcs** [comment]
Please make sure, that only one ShellyMQTT hardware is existing in Domoticz.
Duplicated devices created on occasions when the Shelly device can not be found by its name in the Domoticz database for some reason.

**Comment by jefft4** [comment]
Looks like the plugin had been duplicated in the hardware list.  I've removed the duplicate and will see if that cleans things up.  I still have some duplicate devices after that; is there any way to determine which copy of a Shelly device is the one the plugin is now using?  Both seem to work, which suggests that both still exist in the plugin's cache.

When you say, 'found by its name', do you mean the internal ID 'shelly1-F3A1DB-0-input' or the user-friendly domoticz device name which can - and will - be changed, e.g. 'Hall table lamp'?

**Comment by jefft4** [comment]
Removed the duplicate hardware item.  Restarted domoticz, looked okay.  Then I enabled heartbeat and power; no devices were created so I restarted domoticz again.  Now I have duplicate hardware again.  Aargh!

What causes the hardware to be duplicated, and why only when I've enabled heartbeat & power?  There's only one copy of plugin.py in the folder.

**Comment by jefft4** [comment]
Log...  unfortunately, nothing in there about creating hardware to explain why I have a duplicate Shelly hardware item every time.
[domolog-shelly.log](https://github.com/enesbcs/Shelly_MQTT/files/5119456/domolog-shelly.log)

**Comment by enesbcs** [comment]
From your log:

```
2020-08-24 18:52:41.280  Status: (Shelly devices) Started.
2020-08-24 18:52:41.281  Status: (Shelly devices) Started.
2020-08-24 18:52:41.833  Status: (Shelly devices) Entering work loop.
2020-08-24 18:52:41.833  Status: (Shelly devices) Initialized version 0.5.1
2020-08-24 18:52:41.898  Status: (Shelly devices) Entering work loop.
2020-08-24 18:52:41.898  Status: (Shelly devices) Initialized version 0.5.1
```

There are still two Shelly hardware in your system at a time. Delete one. Or erase full Domoticz database and start a new one...

**Comment by enesbcs** [comment]
> When you say, 'found by its name', do you mean the internal ID 'shelly1-F3A1DB-0-input' or the user-friendly domoticz device name which can - and will - be changed, e.g. 'Hall table lamp'?

The user friendly name can be anything you wish. The internal ID is hardwired to be the MQTT address of the device, the plugin use this address to send commands throught mqtt and to decode shelly device type. This is the reason why custom MQTT prefix option kills this plugin.

**Comment by jefft4** [comment]
Delete the full domoticz database?  Hahahaahaha... Not happening.

I spotted that there were two sets of files in __pycache__, one *36* (original plugin timestamp) and one *37* (today's date), thought that might be the cause of the duplicate hardware returning on every restart.  So, I removed the duplicate hardware again, stopped domoticz, removed the *37* files and restarted domoticz.  Now at I have only one hardware item, though oddly, the *37* files in __pycache__ have returned.

What is the difference between the *36* and *37* files and why do both sets exist here?  Should they both exist?

**Comment by enesbcs** [comment]
> Then I enabled heartbeat and power; no devices were created so I restarted domoticz again. Now I have duplicate hardware again. Aargh!
> What causes the hardware to be duplicated? 

Hardware is duplicated when you are pressing "Add" button instead "Refresh"... Refresh is the good choice to alter existing plugin settings.

**Comment by enesbcs** [comment]
> What is the difference between the _36_ and _37_ files and why do both sets exist here? Should they both exist?
36 and 37 may refer to Python version 3.6 and 3.7. It can be deleted when the plugin is not running, python interpreter recreates cache upon startup.

**Comment by jefft4** [comment]
> > Then I enabled heartbeat and power; no devices were created so I restarted domoticz again. Now I have duplicate hardware again. Aargh!
> > What causes the hardware to be duplicated?
> 
> Hardware is duplicated when you are pressing "Add" button instead "Refresh"... Refresh is the good choice to alter existing plugin settings.

'Update' is the right one when changing settings.  In this case, the duplicate appeared before I'd changed any settings, so it's not the 'Add' mistake.

**Comment by enesbcs** [comment]
> > > What is the difference between the _36_ and _37_ files and why do both sets exist here? Should they both exist?
> > > 36 and 37 may refer to Python version 3.6 and 3.7. It can be deleted when the plugin is not running, python interpreter recreates cache upon startup.
> 
> Interesting that deleting the 37 versions stopped the duplicate hardware from re-creating, then! Perhaps they just contained the duplicated data. Can I remove the 36 versions, given the system is running Python 3.7 ?

Yep they are recreated when needed. If Python 3.7 is the primary and Domoticz uses it, than 36 can be deleted anytime.

**Comment by jefft4** [comment]
Okay, will do.  Just monitoring the logs to check whether dzVents is happy now that the duplicate devices are gone.  I think those are likely to have been the cause of its problems with null data.

**Comment by jefft4** [comment]
Looking better now, everything seems to be working :-)

I'll add in a spare Shelly device and then do some testing by taking it offline to see whether my 'not seen for 30 minutes' event code picks up on the missing heartbeat and then that it recovers properly.

**Comment by enesbcs** [comment]
Domoticz also show red some kind of sensors when they are not reporting for some time... but -online is now a switch device.. maybe it will be much better to change it something else? Maybe a Distance device? https://www.domoticz.com/wiki/Developing_a_Python_plugin#Available_Device_Types

**Comment by jefft4** [comment]
Let's see how it goes; I've set the online device as a push-off switch for now.  My event code monitors the lastUpdate value of the 'online' switch; as long as that reflects the timing of the last message from the Shelly, I think we're good.
If it doesn't work that way, then we could put the timestamp (or minutes since last message) into something like a counter device; that would be easy to test.  Best if it works with lastUpdate, though, as that's the domoticz standard approach.

**Comment by jefft4** [comment]
Testing has gone well; heartbeat correctly detected me cutting the power to a H&T sensor and to a Shelly 1.
- The timestamp on the heartbeat device stopped updating and its lastUpdate time was picked up by my event code as too old.
- The Shelly 1 relay device shows last update at 06:10; it's now 17:16.  The heartbeat for the same Shelly 1 was last updated at 17:15 and every 5 minutes before that, as expected.  So, I know the device is alive and well without the relay state being updated.

Looks good :-)  Hopefully the initial hassles with duplication won't repeat themselves for anyone else!
