### ISSUE TITLE
Shelly Dimmer 2

### ISSUE THREAD

**Issue by sojkin** [enesbcs/Shelly_MQTT#66]
Can you please extend functionality to include Shelly Dimmer 2? I'm trying to control Dimmer 2 with your plugin in Domoticz but only temperature sensor was discovered. It's not possible to set brightness, neither set lights on or off.  There are no switches for that. Should domoticz MQTT plugin work with Dimmer 2 or its something wrong with my setup?

**Comment by enesbcs** [comment]
I am sorry, but i have'nt got this device, nor has any information about it.

**Comment by enesbcs** [comment]
According to these forum entry Dimmer2 already works - without modification.
https://www.domoticz.com/forum/viewtopic.php?f=65&t=25656&p=253716#p251710

**Comment by enesbcs** [comment]
Shelly Dimmer2 tested and works fine with current v0.5.3
