### ISSUE TITLE
Shelly EM / 3EM - ADD Device/function for "Total Power" "Power L1 + Power L2 + Power L3"  

### ISSUE THREAD

**Issue by Gromeiro** [enesbcs/Shelly_MQTT#70]
Hello

I have Shelly 3EM, is working, but I need spcecial function "Total Power, Energy, Total energy"

TOTAL POWER = POWER L1 + POWER L2 + POWER L3 

TOTAL ENERGY = ENERGY L1 + ENERGY L2 +ENERGY L3

TOTAL R_ENERGY = R_ENERGY L1 + R_ ENERGY L2 + R_ENERGY L3

.....

![shelly 3EM](https://user-images.githubusercontent.com/69986487/90813921-340dce00-e320-11ea-99b2-6ece8ea0cb30.PNG)

**Comment by enesbcs** [comment]
As all channel sum total is not sent by the Shelly EM, it has to be add programatically. I guess i can implement it inside the plugin, but it will impact speed as either of the three sub-device updated, i have to find all three subdevice, fetch their values from Domoticz and sum into a fourth virtual device.

**Comment by enesbcs** [comment]
Added a new issue if somebody has idea to do this in the future.
https://github.com/enesbcs/Shelly_MQTT/issues/75
