### ISSUE TITLE
Support for Shelly Uni 

### ISSUE THREAD

**Issue by Luigi8723** [enesbcs/Shelly_MQTT#76]
Hi, 

I have a [Shelly Uni](https://shelly.cloud/products/shelly-uni-smart-home-automation-device/) ordered to connect an[ alaloge ANEMOMETER](https://www.adafruit.com/product/1733) to my Domoticz system.

But i see the Shelly Uni is not supported yet by this plugin.

I this possible to support the Uni? and what do you need from me?
If you're are located in the Netherlands i could send you one to get it supported? 

Edit:
[Found more info on the MQTT settings here](https://shelly-api-docs.shelly.cloud/#shelly-uni-mqtt)

**Comment by enesbcs** [comment]
Shelly Uni is under shipping, i will got it soon and will see what i can do with that.

**Comment by Luigi8723** [comment]
Nice, thanks. I would gladly test when my uni is shipped and anemometer is recieved 👍

**Comment by enesbcs** [comment]
Shelly Uni only sends /input/ /relay/ and /ext_temp/ values. Digital inputs, digital outputs and external temperature sensors are already supported by this plugin.

There are no ADC informations through MQTT from the Uni with the latest firmware, so there are nothing new to support, sorry.

**Comment by Luigi8723** [comment]
> Shelly Uni only sends /input/ /relay/ and /ext_temp/ values. Digital inputs, digital outputs and external temperature sensors are already supported by this plugin.
> 
> There are no ADC informations through MQTT from the Uni with the latest firmware, so there are nothing new to support, sorry.

Wow oke. Did not expect the ADC values not to be send over MQTT. 
Good news about the other parts are allready supported by this plugin. 

Than i have to set some logic in the uni sensor. When ADC value is above x than set DIGITAL output 1 on which will be send of MQTT. 

Thanks for your efforts

**Comment by enesbcs** [comment]
I will ask about ADC & MQTT at the Shelly QA forum.

**Comment by Luigi8723** [comment]
Oke. But this 1.9.3 isn't the lastest firmware ?

**Comment by enesbcs** [comment]
> Oke. But this 1.9.3 isn't the lastest firmware ?

20201202-141748/v1.9.3-rc3@50c6ab57

Its released two days ago, so i guess this is the latest.

**Comment by Luigi8723** [comment]
Than it will be the latest indeed. Mine uni are still not shipped yet so i cannot test. 
But the acual DC value of the ADC is communicated over mqtt with the firmware 1.9.3?

If so i can calculate from this value, the current windspeed.

**Comment by enesbcs** [comment]
Voltage is provided by the UNI:
shellies/shellyuni-xxx/adc/0 3.07
when i am provided ~3V to the ADC. GND also has to be common to be able to read ADC.

**Comment by Luigi8723** [comment]
> Voltage is provided by the UNI:
> shellies/shellyuni-xxx/adc/0 3.07
> when i am provided ~3V to the ADC. GND also has to be common to be able to read ADC. But ADC values only sent when it is changing, if voltage is stable, no values sent.

This wil be fine for me to use in my settup. It will get an fixed power supply. I think the value will change a lot when there is some wind. Will this be a problem for the mqtt network?
The signal is instant and that is what i need to secure my sunscreen for heavy winds.

**Comment by enesbcs** [comment]
> This wil be fine for me to use in my settup. It will get an fixed power supply. I think the value will change a lot when there is some wind. Will this be a problem for the mqtt network?
> The signal is instant and that is what i need to secure my sunscreen for heavy winds.

I do not think that it may be an issue as MQTT packages are small <200 bytes in size, if wifi signal is more than average, it will work just fine. Shelly UNI has an external antenna, so i think it can be positioned for the best signal quality.

**Comment by Luigi8723** [comment]
Allright i will try it out when i have the UNI. 
So i only have to update this plugin on my rasbian system and the ADC data readout will appear in Domoticz?

**Comment by enesbcs** [comment]
Yes, after upgrading plugin to 0.5.5, commit https://github.com/enesbcs/Shelly_MQTT/commit/526534ece354f5b896d136653f8e0773a8085c69

**Comment by Luigi8723** [comment]
Thanks, will test it and give you feedback when the UNI is shipped and attached to the anemometer :)

**Comment by enesbcs** [comment]
![Domoticz_Uni_devices](https://m.blog.hu/bi/bitekmindenhol/image/uni_domo_devs.jpg)

**Comment by Luigi8723** [comment]
Stil waiting on my blackfriday order from shelly. So no update yet, sorry.

**Comment by enesbcs** [comment]
Yep, shipping is a bit slow nowadays from Allterco. I hope the Shelly motion arrives sooner.
I've got my Shelly UNI and 1L from a local seller for testing. :)

**Comment by Luigi8723** [comment]
Hi, i received the uni some time ago, but due to water leakage in house no time to test. So I tested it today and its working.
The only weird thing is, the uni is measuring 0,29Vdc instead of 0,4Vdc. Maybe my power supply is to weak since it giving me no stable 12Vdc but 11,65Vdc.

So I need to find a better power supply and test again 😊 for my setup. But your script I working 😊

**Comment by Luigi8723** [comment]
![uni](https://user-images.githubusercontent.com/28446189/107147326-b9784f80-694d-11eb-89d9-ef2eb2912276.JPG)

**Comment by Luigi8723** [comment]
![Domo](https://user-images.githubusercontent.com/28446189/107147331-c09f5d80-694d-11eb-81ad-ee75c5cf09c1.JPG)

**Comment by Luigi8723** [comment]
@enesbcs is there something to do about update times?
Uni is saying now 0,29Vdc and domoticz 0,33Vdc and last updates 20 minuts ago

**Comment by Luigi8723** [comment]
do i need to change here some settings? had never seen these before
![new settings](https://user-images.githubusercontent.com/28446189/107148909-1546d680-6956-11eb-9929-0361f9a04e59.JPG)

**Comment by enesbcs** [comment]
> do i need to change here some settings? had never seen these before
> ![new settings](https://user-images.githubusercontent.com/28446189/107148909-1546d680-6956-11eb-9929-0361f9a04e59.JPG)

There are no Uni related settings on the plugin side. When data arrives from UNI, it will be refreshed.

**Comment by enesbcs** [comment]
> Edit: when the diffrence is big enough (no sensor attached to the uni) Domoticz will be updated. The uni is now 0Vdc and so domoticz.
> Do you know if this is a issue in Domoticz or in MQTT/ shelly?

You can tell that by setting Debug level to verbose and seeing if Domoticz log shows any incoming ADC MQTT messages.

**Comment by enesbcs** [comment]
> https://shelly-api-docs.shelly.cloud/#mqtt-configuration
> Here is stated the value is pushed every 30 seconds to the mqtt broker. but stil not updated in Domoticz

It is about the default status message. There are nothing speaks about ADC value refresh rate of the UNI. I guess it is based on the change percent of the value..

**Comment by Luigi8723** [comment]
> > Edit: when the diffrence is big enough (no sensor attached to the uni) Domoticz will be updated. The uni is now 0Vdc and so domoticz.
> > Do you know if this is a issue in Domoticz or in MQTT/ shelly?
> 
> You can tell that by setting Debug level to verbose and seeing if Domoticz log shows any incoming ADC MQTT messages.
> 
> There are no such limit in the plugin: when adc value arrives, it will be updated in Domoticz regardless of the previous value.

Oke, i will check what the Uni is sending out. I tried it already in MQTT explorer but the ADC output is nowhere to be seen??
i see its regulairy updates, but these could also be the status of the relays

Will come back to you when i have checked the Domoticz debug logs

**Comment by enesbcs** [comment]
> Oke, i will check what the Uni is sending out. I tried it already in MQTT explorer but the ADC output is nowhere to be seen??

ADC only reports its status when changed, as i see, but i will ask Allterco.

**Comment by Luigi8723** [comment]
thanks, i assume (i must test it) the uni is not updating if the Vdc steps are 0,1Vdc or below. Bigger diffrences are reported as far as i can see.

**Comment by enesbcs** [comment]
> thanks, i assume (i must test it) the uni is not updating if the Vdc steps are 0,1Vdc or below. Bigger diffrences are reported as far as i can see.

Did you try with 12VDC supply and 12V range? Smaller range means better precision. Default range is 30V which means 0.03V accuracy. (with 12V range = 0.01V)

**Comment by Luigi8723** [comment]
> > thanks, i assume (i must test it) the uni is not updating if the Vdc steps are 0,1Vdc or below. Bigger diffrences are reported as far as i can see.
> 
> Did you try with 12VDC supply and 12V range? Smaller range means better precision. Default range is 30V which means 0.03V accuracy. (with 12V range = 0.01V)

Yes, this is the setting which the uni is on from the beginning of my test.

**Comment by Luigi8723** [comment]
Just did some measurements the sensor is giving 0.4vdc as output, but he uni is seeing 0.29vdc so the uni is a bit off. When changing the setting to 0-30vdc range its giving 0.12vdc. So the uni is also calculating the voltage

The adc is connected to sensor output with the White wire.  And the ground of the sensor on green. As shown in the uni guide.

I have a second uni. Maybe i Will do a second test with this one.

With your test. Was the uni measuring the right values? And how did you connect the adc?

**Comment by enesbcs** [comment]
> The adc is connected to sensor output with the White wire. And the ground of the sensor on green. As shown in the uni guide.

Thats right, it should work fine with common GND.

> With your test. Was the uni measuring the right values? And how did you connect the adc?

I've test that with only a very simple method: by connecting Sensor_VCC out to ADC in. :) So GND is common, and output is reported as 3.07V. There are almost +/10% deviance from 3.3V. I've got an alterable DC power supply somewhere, if i find it, i can make more tests.

**Comment by Luigi8723** [comment]
Smart ;) never tought of that. Will do the same and check the output. 
And will do a test with my second uni. 

I tried also with the common ground instead of the sensor ground. No difference in the voltage reading.

I measured the output of my sensor with a simple multimeter and this was 4vdc.

If you could do some tests with low voltage steps 0.01vdc and domoticz we could see if there is an error in my uni or in the software of the uni.

**Comment by Luigi8723** [comment]
Shelly uni seems to be fine. I have also 3.08vdc when i connect the yellow 3.3vdc on the sensor input. Still the messurement its not that accurate. But that not my biggest problem.
The refresh rate of the adc value is my biggest problem. Its online reporting with big differences more than 0.07vdc??

**Comment by Luigi8723** [comment]
I have submitted a ticket to  Allterco about the report time and the weird ADC voltage measuring:
I will post the reactions here.

**i have send them this:**
I have some issues with the Shelly Uni. I am using the ADC function of the uni with a anemometer (this one: https://www.adafruit.com/product/1733)
The uni is running on firmware version: 20201124-093042/v1.9.0@57ac4ad8
With the ADC setting to 0-12 Vdc, and MQTT enabled.

Issue 1: wrong Vdc measurement in the shelly Uni??
The Uni is connect to a 24 Vdc power supply (also tested with a 12Vdc power supply same results)
The anemometer sensor is connected with the output (0,4-2 Vdc) to the White ADC input wire. And also to the same 24 Vdc power supply. The ground is connected to the common ground (black) (also tested with the green internal Ground.
When I measure the output of the anemometer with a simple multimeter I see 0,4 Vdc as specified by the manufacturer. 
But when I attach the sensor output to the shelly uni, the uni is giving me 0,29 Vdc as output voltage.
Why is there difference in the VDC readings?

Issue 2:
When is the Uni reporting to MQTT? 
I see updates done by bigger differences in the ADC voltage to my MQTT Broker (Mosquitto) and to my Domoticz system. 
But when the differences are smaller approx.  0,07Vdc this is not updated to Mosquitto or Domoticz anymore. So my Domoticz is sticking to 0,36Vdc and the Shelly Uni is back to “normal” at 0,29Vdc.
Is the ADC voltage also reported regularity every 30 seconds  of only with differences bigger than X?
my sensor range is small 0,4Vdc -2Vdc so I would like to see also reports on smaller differences or every 30 seconds, is this possible?

**Comment by Luigi8723** [comment]
so, couple of day further I got more information from shelly:

The minimum report value of the Uni is 0.10VDc so this why I get differences between Domoticz and the Shelly Uni.

At the moment they are still checking my the measurements are different on 2 uni's ( I think the measurements are to small)

**Comment by enesbcs** [comment]
Closed as implemented
