### ISSUE TITLE
Frequent update of ShellyBulbDuo

### ISSUE THREAD

**Issue by MichaelVanDijk** [enesbcs/Shelly_MQTT#77]
Every time MQTT gets a message from a  ShellyBulbDuo the domoticz-device is updatet. Even if nothing has changed. For other devices (e.g. ShellyVintage-Dimmer) this is not the case. The ShellyVintage device is in domoticz only updated is something is changed.
When you have specified a event which is triggered by a ShellyBulbDuo device, the event is executed constantly.

**Comment by enesbcs** [comment]
I guess that some error happens in plugin.py between Line 1069 and Line 1075. I will test it.

**Comment by enesbcs** [comment]
Fixed in commit https://github.com/enesbcs/Shelly_MQTT/commit/a0e2acb8e87f7d14c55b436f735c4f8092959827

**Comment by MichaelVanDijk** [comment]
Changing the lines resolves the problem. Thanks! Working like a charm again.
