### ISSUE TITLE
Shelly 1L also works without further ado!

### ISSUE THREAD

**Issue by salopette** [enesbcs/Shelly_MQTT#78]
Hello, I got my Shelly 1L yesterday, it works without any problems!
Please enter the list of supported devices!
Thanks for the great plug-in!

![sshot-1](https://user-images.githubusercontent.com/32480002/102008727-e552cc80-3d32-11eb-85b7-dca9e3b4e104.jpg)

**Comment by enesbcs** [comment]
thank you for your feedback! I've just got my Shelly 1L and tested also. 
Works indeed, but a little strange to me, that it provides energy readings also, despite it does not have any power measurement ic onboard.
