### ISSUE TITLE
Duo RGBW G10 aka "shellycolorbulb" device

### ISSUE THREAD

**Issue by enesbcs** [enesbcs/Shelly_MQTT#81]
According to user reports this device works differently than the older "shellybulb", color change is not currently possible.
As official API is not yet updated, support can not be added at this time.
https://www.domoticz.com/forum/viewtopic.php?p=266942#p266942

**Comment by pagocs** [comment]
Hmm, interesting because based on my experience the color change is work perfectly with Duo RGB.

**Comment by enesbcs** [comment]
> Hmm, interesting because based on my experience the color change is work perfectly with Duo RGB.

The G10 variant?

**Comment by pagocs** [comment]
Sorry, I missed this. I meant the E27 variant.

**Comment by darrepac** [comment]
After too much wait the documentation has been eventually updated! https://shelly-api-docs.shelly.cloud/#shelly-bulb-rgbw-settings
Now appear the shellycolorbulb and my GU10 will eventually work!
Eager to see the new version ;)

**Comment by enesbcs** [comment]
According the API, colorbulb is exactly the same as an rgbw2 color device.
I've removed legacy ison command, replaced with turn as it has to be work on every actual firmware.
https://github.com/enesbcs/Shelly_MQTT/commit/0636aee74b8af4931173b2c976ddcd765e6add02

**Comment by darrepac** [comment]
How can I test this new plugin version with plugin-manager, is there a way?

**Comment by enesbcs** [comment]
https://github.com/ycahome/pp-manager

'To continuously update selected plugin: Select desired plugin from "Domoticz Plugin" field put "Selected" on "Auto Update" drop-down box and press update'

**Comment by darrepac** [comment]
Sorry, I am using https://github.com/stas-demydiuk/domoticz-plugins-manager and it is not working as expected... will open issue on their repository

**Comment by enesbcs** [comment]
closed as no feedback regarding rgbw integration

**Comment by darrepac** [comment]
Well I am still waiting for the issue to be look at : https://github.com/stas-demydiuk/domoticz-plugins-manager/issues/21
Seems I need to change the plugin manager
