### ISSUE TITLE
Add support for Shelly 3EM

### ISSUE THREAD

**Issue by Myrddinlefou** [enesbcs/Shelly_MQTT#83]
Hello, 

I have a Shelly 3EM and I try to add support for my powermeter with your plugin but it is hard to understand where I have to add some code.
I think it is like Shelly EM, but with 3 emeter : 0, 1 and 2, but maybe I do not have a true evaluation of the work.
Can you explain me where I have to add something ?
Thank's a lot

**Comment by enesbcs** [comment]
EM and EM3 is almost the same device, and it is already implemented.

shellies/shellyem-<deviceid>/emeter/<i>/energy

shellies/shellyem3-<deviceid>/emeter/<i>/energy

I guess you did not enabled power reading in plugin settings page.

**Comment by enesbcs** [comment]
FYI Shelly 3EM reported to work with this plugin several times:
https://github.com/enesbcs/Shelly_MQTT/issues/70
https://github.com/enesbcs/Shelly_MQTT/issues/45
