### ISSUE TITLE
Shelly H&T Batttery

### ISSUE THREAD

**Issue by siether** [enesbcs/Shelly_MQTT#85]
Hello,

The plugin is working flawless with domoticz.
Lately I've added an Shelly H&T sensor in my setup.
Is it possible to  send the battery status to domoticz too?
The only device that's created is the H&T sensor.

Greetings from a happy user!
Sieth

**Comment by enesbcs** [comment]
Do you think about a separated battery device in Domoticz?

Battery level is already included in the temperature data in the Domoticz standard way:
Devices[iUnit].Update(nValue=0,sValue=str(curval),BatteryLevel=int(mval))
As battery is a parameter of every value in Domoticz. Low battery warning is 10% but can be adjusted in Domoticz Other settings, and will notify you when any device go below the limit by the way you setted up at notifications.

You can check Domoticz wiki about other manual methods:
https://www.domoticz.com/wiki/Battery_level_check

**Comment by enesbcs** [comment]
Closed as no more feedbacks
