### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by WouterHagedoorn** [enesbcs/Shelly_MQTT#86]
The system and script were stable until this evening . I have my new shelly motion arriving today so I decided to do an update of the script.
- Fist trial was to only take the plugin.py and overwrite the old one. This resulted in all my domoticz sensors getting red.
- I decided to take the risk (of dubble sensors)  and did the git pull update. Sensors are alive but not responding. Domoticz give following error:

_(Shelly_MQTT) Your Domoticz Python environment is not functional! MQTT client import error: No module named 'mqtt'_

When I look in Domoticz Hardware I now have 2 pieces of MQTT hardware ... **Shelly_MQTT** and **mqtt**
- I tried to de activate them both but all devices are coupled on Shelly_MQTT, allthough I put the 1883 port in and pressed update the port does not show in the hardware table.

My Sonoff devices on MQTT still work fine and I can see the MQTT massages in MQTT Explorer. 

So I think I'm close but don't know where to look next.

**Comment by enesbcs** [comment]
>     * Fist trial was to only take the plugin.py and overwrite the old one. This resulted in all my domoticz sensors getting red.
> 
>     * I decided to take the risk and did the git pull update. Sensors are alive but not responding. Domoticz give following error:
> 
> 
> _(Shelly_MQTT) Your Domoticz Python environment is not functional! MQTT client import error: No module named 'mqtt'_

Yes, as mqtt.py is also part of the plugin. Upgrading only one file will result similar errors.
- Please do yourself a favour and use a Domoticz plugin manager to update python plugins:
 https://github.com/stas-demydiuk/domoticz-plugins-manager
- Do not use multiple shelly_mqtt instances on hardware page, as it will surely not work.
- If there are multiple Python3 versions on the Domoticz server, leave only one, remove other versions
- Please restart Domoticz after updating any plugin!

> My Sonoff devices on MQTT still work fine and I can see the MQTT massages in MQTT Explorer.

Unrelated as Domoticz integrated MQTT client is not python based.

**Comment by WouterHagedoorn** [comment]
Sorry, I thought I followed the advise to only update the plugin.py
I will use the plugin manager and see if that does the trick. Thanks for your quick response.

**Comment by WouterHagedoorn** [comment]
Tanks, uninstall and reinstall and issue solves. My suggestion is promote this option in your update suggestions for people like me ;-)
