### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by rolfie23** [enesbcs/Shelly_MQTT#91]
Goodday,

Installed an update recently, but now the log of Domoticz is filled constantly by the plugin! For example:
`2021-04-14 11:03:38.149 (Shelly MQTT) Device data: shelly1pm-E09806AA026B-0-energy value: 0.0;11262.194 lastupdate: 2021-04-14 11:03:28`
Please let us choose if it must be in the log or not! I use log for debugging, and with this makes it harder (almost every 2 seconds a line in the log).

**Comment by enesbcs** [comment]
Its added by pagocs at PR https://github.com/enesbcs/Shelly_MQTT/commit/9b90a94b39eeb2bea87c049256299869da08772a#diff-08655555cc53ca79554ba180d1ae7e6ebe5c9b0a25e1772ce248fdd8b83dab34 2021.01.18

**Comment by rolfie23** [comment]
When will the next release be? Found the part where it's added to the log, can exclude it so it's gone off the log, but then the git pull won't work normally.

**Comment by enesbcs** [comment]
You are right, fixed in commit https://github.com/enesbcs/Shelly_MQTT/commit/f359c18dba411a25ed9138a2438ad658dc5f1d2f just now

**Comment by rolfie23** [comment]
Great, will try in few hours!

**Comment by rolfie23** [comment]
It's a lot less, but in rule 551 there is also a log function for the update parameter. Can you switch that also to debug?

**Comment by enesbcs** [comment]
Yes of course, updated.

**Comment by rolfie23** [comment]
Thanks! Work like a charm now!
